/**
 * Kanban datasource
 */

 export let kanbanData: Object[] = [
    {
      Id: 'Open - 11',
      Title: 'Task - 29001',
      Status: 'Open',
      Summary: '',
      Type: 'Story',
      Priority: 'Low',
      Tags: '',
      Estimate: 3.5,
      Assignee: 'Nancy Davloio',
      RankId: 1,
      Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Written test - 24',
      Title: 'Task - 29002',
      Status: 'InProgress',
      Summary: '',
      Type: 'Improvement',
      Priority: 'Normal',
      Tags: '',
      Estimate: 6,
      Assignee: 'Andrew Fuller',
      RankId: 1,
      Color: '#673AB8',
      ClassName: '',
    },
    {
      Id: 'Amirdharashan A',
      Title: 'Task - 29003',
      Status: 'Open',
      Summary: 'intellectyx Data science private li...',
      Type: 'Others',
      Priority: 'Critical',
      Tags: '',
      Estimate: 5.5,
      Assignee: 'Janet Leverling',
      RankId: 2,
      // Color: '#1F88E5',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Vijay Bhupathi V',
      Title: 'Task - 29004',
      Status: 'InProgress',
      Summary: 'Topclass Entertainment LLP',
      Type: 'Bug',
      Priority: 'Critical',
      Tags: '',
      Estimate: 2.5,
      Assignee: 'Janet Leverling',
      RankId: 2,
      // Color: '#E64A19',
      ClassName: 'rating, rating, rating, rating',
    },
    {
      Id: 'Task 5',
      Title: 'Task - 29005',
      Status: 'Review',
      Summary: 'Fix the issues reported by the customer.',
      Type: 'Bug',
      Priority: 'Low',
      Tags: 'Customer',
      Estimate: '3.5',
      Assignee: 'Steven walker',
      RankId: 1,
      Color: '#E64A19',
      ClassName: ''
    },
    {
      Id: 'Contacted - 6',
      Title: 'Task - 29007',
      Status: 'Validate',
      Summary: '',
      Type: 'Improvement',
      Priority: 'Low',
      Tags: '',
      Estimate: 1.5,
      Assignee: 'Robert King',
      RankId: 1,
      Color: '#673AB8',
      ClassName: '',
    },
    {
      Id: 'Task 7',
      Title: 'Task - 29009',
      Status: 'Review',
      Summary: 'Fix the issues reported in Safari browser.',
      Type: 'Bug',
      Priority: 'Critical',
      Tags: 'Fix,Safari',
      Estimate: 1.5,
      Assignee: 'Nancy Davloio',
      RankId: 2,
      Color: '#E64A19',
      ClassName: ''
    },
    {
      Id: 'Culture fit round - 4',
      Title: 'Task - 29010',
      Status: 'Close',
      Summary: '',
      Type: 'Story',
      Priority: 'Low',
      Tags: '',
      Estimate: 5.5,
      Assignee: 'Margaret hamilt',
      RankId: 3,
      Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Akash P',
      Title: 'Task - 29011',
      Status: 'Validate',
      Summary: 'Centre',
      Type: 'Story',
      Priority: 'High',
      Tags: '',
      Estimate: 1,
      Assignee: 'Steven walker',
      RankId: 1,
      // Color: '#02897B',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Vimal Kumar',
      Title: 'Task - 29015',
      Status: 'Open',
      Summary: 'Sirius Computer Solution',
      Type: 'Story',
      Priority: 'High',
      Tags: '',
      Estimate: 5.5,
      Assignee: 'Margaret hamilt',
      RankId: 4,
      // Color: '#02897B',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'M janasri',
      Title: 'Task - 29016',
      Status: 'InProgress',
      Summary: 'TCS',
      Priority: 'Critical',
      Type: 'Bug',
      Tags: '',
      Estimate: 2.5,
      Assignee: 'Janet Leverling',
      RankId: 4,
      // Color: '#E64A19',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Mohamed Mubarak',
      Title: 'Task - 29016',
      Status: 'InProgress',
      Summary: 'MangoDB ',
      Priority: 'Critical',
      Type: 'Bug',
      Tags: '',
      Estimate: 2.5,
      Assignee: 'Janet Leverling',
      RankId: 4,
      // Color: '#E64A19',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Jithin Sajay A',
      Title: 'Task - 29016',
      Status: 'InProgress',
      Summary: '',
      Priority: 'Critical',
      Type: 'Bug',
      Tags: '',
      Estimate: 2.5,
      Assignee: 'Janet Leverling',
      RankId: 4,
      // Color: '#E64A19',
      ClassName: '',
    },
    {
      Id: 'Task 12',
      Title: 'Task - 29017',
      Status: 'Review',
      Summary: 'Fix the issues reported in data binding.',
      Type: 'Story',
      Priority: 'Normal',
      Tags: 'Databinding',
      Estimate: '3.5',
      Assignee: 'Janet Leverling',
      RankId: 4,
      Color: '#02897B',
      ClassName: 'rating, rating, rating',
    },
    {
      Id: 'Dineshkumar',
      Title: 'Task - 29018',
      Status: 'Close',
      Summary: 'Wipro Technologies',
      Type: 'Story',
      Priority: 'Critical',
      Tags: '',
      Estimate: 2,
      Assignee: 'Andrew Fuller',
      RankId: 4,
      // Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Gayathri L',
      Title: 'Task - 29019',
      Status: 'Validate',
      Summary: 'Katomaran Technologies Pvt Ltd',
      Type: 'Story',
      Priority: 'Low',
      Tags: '',
      Estimate: 1.5,
      Assignee: 'Margaret hamilt',
      RankId: 1,
      Color: '#02897B',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Pradeep K',
      Title: 'Task - 29020',
      Status: 'Close',
      Summary: 'Cognizant Technologies',
      Type: 'Story',
      Priority: 'High',
      Tags: '',
      Estimate: 2.5,
      Assignee: 'Margaret hamilt',
      RankId: 5,
      // Color: '#02897B',
      ClassName: 'rating, rating,rating, rating, rating',
    },
    {
      Id: 'Hemachandru K',
      Title: 'Task - 29021',
      Status: 'Close',
      Summary: 'Paypal client',
      Type: 'Others',
      Priority: 'Critical',
      Tags: '',
      Estimate: 1.5,
      Assignee: 'Steven walker',
      RankId: 6,
      // Color: '#1F88E5',
      ClassName: '',
    },
    {
      Id: 'Sruthi Radhakrishnan',
      Title: 'Task - 29022',
      Status: 'Close',
      Summary: 'Konnectify',
      Type: 'Story',
      Priority: 'Critical',
      Tags: '',
      Estimate: 5.5,
      Assignee: 'Janet Leverling',
      RankId: 7,
      // Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'S Suresh',
      Title: 'Task - 29023',
      Status: 'Validate',
      Summary: 'Synopsis',
      Type: 'Story',
      Priority: 'Critical',
      Tags: '',
      Estimate: 1,
      Assignee: 'Nancy Davloio',
      RankId: 1,
      Color: '#02897B',
      ClassName: 'rating, rating, rating, rating',
    },
    {
      Id: 'Arun Prakash A',
      Title: 'Task - 29023',
      Status: 'Validate',
      Summary: 'IIT Madras',
      Type: 'Story',
      Priority: 'Critical',
      Tags: '',
      Estimate: 1,
      Assignee: 'Nancy Davloio',
      RankId: 1,
      Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Technical round - 3',
      Title: 'Task - 29024',
      Status: 'Testing',
      Summary: '',
      Type: 'Story',
      Priority: 'Normal',
      Tags: '',
      Estimate: 0.5,
      Assignee: 'Nancy Davloio',
      RankId: 5,
      Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Arun Kumar',
      Title: 'Task - 29024',
      Status: 'Testing',
      Summary: 'Vidhya Skill School',
      Type: 'Story',
      Priority: 'Normal',
      Tags: '',
      Estimate: 0.5,
      Assignee: 'Nancy Davloio',
      RankId: 5,
      // Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Midhun Krishna S',
      Title: 'Task - 29024',
      Status: 'Testing',
      Summary: 'Cognizant',
      Type: 'Story',
      Priority: 'Normal',
      Tags: '',
      Estimate: 0.5,
      Assignee: 'Nancy Davloio',
      RankId: 5,
      // Color: '#02897B',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Gowri Shankar S',
      Title: 'Task - 29024',
      Status: 'Testing',
      Summary: 'BM Technovations 2',
      Type: 'Story',
      Priority: 'Normal',
      Tags: '',
      Estimate: 0.5,
      Assignee: 'Nancy Davloio',
      RankId: 5,
      // Color: '#02897B',
      ClassName: '',
    },
    {
      Id: 'Jayakrishnan Duraisamy',
      Title: 'Task - 29025',
      Status: 'Open',
      Summary: 'Lakeba IT Solution',
      Type: 'Improvement',
      Priority: 'Low',
      Tags: '',
      Estimate: 3.5,
      Assignee: 'Andrew Fuller',
      RankId: 5,
      Color: '#673AB8',
      ClassName: 'rating, rating, rating, rating, rating',
    },
    {
      Id: 'Affan Ahmed Syed',
      Title: 'Task - 29025',
      Status: 'Open',
      Summary: 'Smart parking',
      Type: 'Improvement',
      Priority: 'Low',
      Tags: '',
      Estimate: 3.5,
      Assignee: 'Andrew Fuller',
      RankId: 5,
      Color: '#673AB8',
      ClassName: '',
    },
  ];
  